version: '3'

services:
  db:
    image: "mysql:latest"
    container_name: "letscard-mysql"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"

volumes:
  mysql-data: